### ISSUE TITLE
Lack of coverage

### ISSUE THREAD

**Issue by cnlohr** [pvvx/SDKnoWiFi#2]
Hey, this isn't really an issue but I'm not sure how else to contact you.  I had no idea this project existed when I was making mine, I only saw your other, somewhat larger one with wifi.

I've updated my project page and commented back on twitter, etc.  I hope you are not upset.  You beat me to the completion of this by two years!

Thank you again for all of your excellent work!

**Comment by MrAda** [comment]
I came over from CNLOHR's project.  He says this has WIFI but your project description indicates no WIFI.  Which is it?

**Comment by cnlohr** [comment]
Uuuhhhhhhh I think there is some confusion.  Mind pointing me at what I actually said?

**Comment by MrAda** [comment]
you wrote "when I was making mine, I only saw your other, somewhat larger one with wifi" and they have "pvvx/SDKnoWiFi".  You implied they had WIFI, and they indicate that it has no WIFI.  I'd consider looking at this if it did have WIFI as that is what I need.

**Comment by cnlohr** [comment]
Oh! No.  So, he has another project. https://github.com/pvvx/esp8266web I believe.  I didn't know this project (noWifi) existed.

**Comment by MrAda** [comment]
@cnlohr Ok.  I was getting desperate today and was looking on trying to use my RPI3 for my project.  Saves me from having to crawl in my attic to update the 24V transformer!

**Comment by cnlohr** [comment]
I don't quite understand your comment... should this be marked closed?

**Comment by MrAda** [comment]
I am guessing this can be closed.  My comment was because I am working on a thermostat project.  The 24VAC input is coming from a transformer which is only 35VA  about 1.5 amps.  Not enough juice to run the project if I am using  a Pi and a screen.

**Comment by cnlohr** [comment]
Hmm, just wondering, why not use Arduino, or the C (ESP_NON_OS, FreeRTOS) environments?

**Comment by MrAda** [comment]
I already purchased a pi3 so that is why i didn't go with arduino.   I know they aren't expensive but I am trying not to spend money until I gret a solution.  I tried looking at the FreeRTOS stuff but I was unsure if it would work with the NODEMCU.  I can revisit.

**Comment by cnlohr** [comment]
No no, I am specifically saying use NodeMCU hardware with Arduino environment.  NodeMCU hardware also works with ESP_NON_OS and FreeRTOS.

**Comment by MrAda** [comment]
Actually given my low power (35 VA @ 24V @ 1.5 PF = about 1 Amp), I cannot use the NODEMCU with an Arduino or Pi without changing out the transformer.  I had planed to use the NODEMCU as a stand-alone controller device as it doesn't pull that much amps.  I have a 4-relay board to control my wires for the HVAC.  Just need that NODEMCU to communicate with my wireless server and be able to broadcast its state to another unit so that they both can coordinate their operations.

**Comment by cnlohr** [comment]
If you are using NodeMCU:Hardware, you don't need Arduino:Hardware or Pi:Hardware.  You can run Arduino:Software on NodeMCU:Hardware, or NodeMCU:Software on NodeMCU:Hardware, but you absolutely do not need any more hardware than a NodeMCU:Hardware.   If you run into a pinch with power, you can always use a buck supply, like this: https://www.amazon.com/DROK-Converter-Step-down-Transformer-Regulator/dp/B00SY37S00  Though they come much more cheaply on ebay.

**Comment by MrAda** [comment]
I have never heard that one could use Arduino Software on the Node MCU hardware.  I presume that Arduino and NodeMCU hardware usese same chip?  I have found a buck supply that will take my 24VAC to DC power.  Thanks.

**Comment by cnlohr** [comment]
No.  They use very different chips.  But, you can use it none-the-less. See: https://github.com/esp8266/Arduino .  Arduino software is processor independent.  There just happens to be hardware bearing the name "Arduino"

WRT the buck supply, don't forget to use a bridge and capacitor.  Also, I think we should close this thread, since it is unrelated to pvvx's project?

**Comment by MrAda** [comment]
I just wanted to state here, so others can benefit, that Charles is right that using the Arduino tool targetting an ESP8266 is very doable and I have been able to proceed forward with my NODEMCU/ESP8266 project.

**Comment by cnlohr** [comment]
I think we should close the issue?

**Comment by MrAda** [comment]
Concur
